accounts/urls.py
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetCompleteView, PasswordResetConfirmView
from django.contrib.auth.views import login, logout
from django.urls import path, reverse_lazy, re_path

from . import views
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetCompleteView, PasswordResetConfirmView
from django.contrib.auth.views import login, logout
from django.urls import path, reverse_lazy, re_path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),

    path('changePassword/', PasswordChangeView.as_view(success_url=reverse_lazy('accounts:password_change_done')),
         name='password_change'),
    path('passwordChanged/', PasswordChangeDoneView.as_view(), name='password_change_done'),



    path('resetPassword/', PasswordResetView.as_view(success_url=reverse_lazy('accounts:password_reset_done')),
         name='password_reset'),
    path('passwordReset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),


    re_path(r'passwordResetConfirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            PasswordResetConfirmView.as_view(success_url=reverse_lazy('accounts:password_reset_complete')),
            name='password_reset_confirm'),

    path('passwordReset/complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('register/', views.SignUp, name='register')

]

socialsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('oauth/', include('social_django.urls', namespace='social'))

]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.models import User


class SignUpForm(forms.ModelForm):
    password = forms.CharField(label='password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='password2', widget=forms.PasswordInput)

    # gender = forms.RadioSelect(choices=('M', 'F'))

    class Meta:
        model = User
        fields = ['username', 'first_name', 'email']

    def cleanpassword2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Password did not match')
        return cd['password']

accounts/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

from .forms import SignUpForm


# Create your views here.
# @login_required
class HomeView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        return super().get_context_data(title='Homepage')


def SignUp(request):
    if request.method == 'POST':
        user_form = SignUpForm(request.POST)

        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            return render(request, 'accounts/register_done.html', {'new_user': new_user})
    else:
        user_form = SignUpForm

    return render(request, 'accounts/register.html', {'user_form': user_form})

accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% block content %}
    <h1>Create account</h1>
    <p>Please enter your details.</p>
    <form action="" method="post">
        {% csrf_token %}
        {{ user_form.as_p }}
        <p><input type="submit" value="Submit"/></p>
    </form>

{% endblock %}

accounts/templates/accounts/register_done.html
{% extends 'base.html' %}
{% block content %}
    <h1>Welcome {{ new_user.first_name }},</h1>
    <p> Your registration done successfully</p>
    <p><a href="{% url 'accounts:login' %}">Login</a></p>
{% endblock %}

accounts/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Social site</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Ratnesh</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
            aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Features</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Pricing</a>
            </li>
        </ul>
        <span class="navbar-text">
            {% if request.user.is_authenticated %}
                <p>Hello Ratnesh  <a href="{% url 'accounts:logout' %}">Logout</a> </p>
            {% else %}
                <p><a href="{% url 'accounts:login' %}">Login</a> </p>
            {% endif %}

    </span>
    </div>
</nav>
{% block content %}
{% endblock %}
</body>
</html>

accounts/templates/home.html
{% extends 'base.html' %}
{% block content %}
    <h1>Welcome to Dashboard</h1>

    <p><a href="{% url 'accounts:password_change' %}">Change Password</a></p>
    <p>If you have not registered click here<a href="{% url 'accounts:register' %}">Register</a></p>

{% endblock %}0